Repository bounswe/bounswe2020group2, pull requests merged in 2020-05, with the labels that each got.

#81 Add maps feature with reverse geocoding
  practice_app/.prettierrc
  practice_app/components/MapView.js
  practice_app/components/MapView.module.css
  practice_app/config.js
  practice_app/package-lock.json
  practice_app/package.json
  practice_app/pages/api/getLocationInfo.js
  practice_app/pages/api/getRandomNumber.js
  practice_app/pages/example.spec.js
  practice_app/pages/index.js
  practice_app/public/marker.png
  practice_app/services/getLocationInfo.js
  practice_app/services/getLocationInfo.spec.js
Labels: help wanted, priority: high, status: in progress, status: needs review, type: discussion, type: front-end, type: suggestion, who: group

#83 Furkan nane covid-19 statistics pull request
  README.md
  practice_app/pages/api/getStatistics.js
  practice_app/pages/api/getStatistics.test.js
  practice_app/pages/api/getStatisticsModule.js
  practice_app/pages/index.js
Labels: effort: low, priority: high

#86 Added the create product feature.
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#87 Add create product set function
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#88 Added the add reference image feature.
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#89 Add get similar product function
  practice_app/pages/api/getSimilarProducts.js
Labels: effort: medium, type: back-end

#90 Add update product function
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#93 Added the filter products feature.
  practice_app/pages/api/filter.js
Labels: effort: medium, type: back-end

#94 Added the list product sets feature.
  practice_app/pages/api/getSets.js
Labels: effort: medium, type: back-end

#95 Add get all products function
  practice_app/pages/api/getAllProducts.js
Labels: effort: medium, type: back-end

#96 Add get products in set function
  practice_app/pages/api/getProductsInSet.js
Labels: effort: medium, type: back-end

#97 Add delete product function
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#98 Added delete set feature.
  practice_app/pages/api/getProductCatalog.js
Labels: effort: medium, type: back-end

#103 New unit tests for maps functionality
  practice_app/pages/api/getCountriesWithMaxDeaths.js
  practice_app/pages/api/getCountriesWithMaxDeaths.test.js
  practice_app/pages/api/getCountriesWithMaxDeathsModule.js
  practice_app/services/getLocationInfo.js
  practice_app/services/getLocationInfo.spec.js
Labels: effort: low

#91 Reddit branch merge
  practice_app/package-lock.json
  practice_app/package.json
  practice_app/pages/api/exampleRedditData.json
  practice_app/pages/api/getRedditData.js
  practice_app/pages/api/getRedditData.test.js
  practice_app/pages/api/getRedditDataModule.js
  practice_app/pages/index.js
Labels: effort: high

#105 Translation API
  practice_app/pages/api/getTranslation.js
  practice_app/pages/api/getTranslation.test.js
  practice_app/pages/api/getTranslationModule.js
  practice_app/pages/api/isoLanguages.json
  practice_app/pages/index.js
Labels: effort: medium, type: back-end

#106 Google Product Search&Vision API
  practice_app/components/SimilarProduct.js
  practice_app/cssColors.json
  practice_app/package-lock.json
  practice_app/package.json
  practice_app/pages/api/getAllProducts.js
  practice_app/pages/api/getProductCatalog.js
  practice_app/pages/api/getProductCatalog.test.js
  practice_app/pages/api/getProductsByCategory.js
  practice_app/pages/api/getProductsInSet.js
  practice_app/pages/api/getSets.js
  practice_app/pages/api/getSimilarProducts.js
  practice_app/pages/index.js
  practice_app/services/getConvertedPrice.js
Labels: effort: high, priority: high, status: needs review, type: back-end
